name: Create Zip File

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create directories
        run: |
          mkdir -p Payload2Super/branch
          cp -r ./* Payload2Super/branch
          rm -rf Payload2Super/branch/debloat.txt

      - name: Compress files
        run: zip -j Payload2Super.zip Payload2Super/branch/*

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Payload2Super
          path: Payload2Super.zip
